# .travis.yml
#language: ruby
# rvm:
#   - "1.8.7"
#   - "1.9.2"
#   - "1.9.3"
#   - jruby-18mode # JRuby in 1.8 mode
#   - jruby-19mode # JRuby in 1.9 mode
#   - rbx-18mode
#   - rbx-19mode


before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - mysql -e 'create database myapp_test;'
  - mysql -e 'create database myapp_dev;'
  # - sleep 3 # give Web server some time to bind to sockets, etc
  - bundle install
  
   #- bundle update
  # - rackup --port 9999
  - bundle exec cucumber
  - bundle exec rspec
  
notifications:
  email:
    - tran.dat@mulodo.com
  
# before_script:
#  - mysql -e 'create database myapp_test;'
#  - mysql -e 'create database myapp_dev;'
  # - "export DISPLAY=:99.0"
  # - "sh -e /etc/init.d/xvfb start"
  #- sleep 3 # give xvfb some time to start
  #- bundle exec rackup  # start a Web server
  #- sleep 3 # give Web server some time to bind to sockets, etc
  
# script:
#  - rackup --port 9999
#  - bundle exec cucumber
#  - bundle exec rspec

